# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Main

on:
  push:
    branches: [ parsampsh-create-workflow ]
  pull_request:
    branches: [ parsampsh-create-workflow ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Run tests
      run: |
        make all
    - name: Test build program
      run: |
        python3 -m pip ./src/pashmak.py --onefile
        ./dist/pashmak -v
