name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Run tests
      run: make all

    name: Linux Python ${{ matrix.python }}

  Linux_Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup pyinstaller
      run: |
        pip3 install pyinstaller
    - name: Build
      run: |
        make all
        python3 -m PyInstaller src/pashmak.py --onefile
        ./dist/pashmak -v

    name: Linux Build

  Windows_Python_3_6:

    runs-on: windows-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Run tests
      run: |
        python scripts.py build-modules
        python scripts.py update-headers
        python scripts.py build-doc
        python tests\run.py

    name: Windows Python ${{ matrix.python }}

  Windows_Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup pyinstaller
      run: |
        pip install pyinstaller
    - name: Build
      run: |
        python scripts.py build-modules
        python scripts.py update-headers
        python scripts.py build-doc
        python tests\run.py
        python -m PyInstaller src\pashmak.py --onefile
        dist/pashmak.exe -v

    name: Windows Build
