name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unix_tests:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Setup pyinstaller
      run: |
        pip3 install pyinstaller
    - name: Test
      run: |
        make all
        make
        ./dist/pashmak -v

    name: ${{ matrix.os }} Python ${{ matrix.python }}

  windows_tests:

    runs-on: windows-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Setup pyinstaller
      run: |
        pip install pyinstaller
    - name: Test
      run: |
        .\win-configure.bat
        python -m PyInstaller src\pashmak.py --onefile
        dist\pashmak.exe -v

    name: Windows Python ${{ matrix.python }}
